name: easypost
root: ~/easypost

windows:
  - editor:
      layout: main-vertical
  - logs:
      logs: tail -f log/easypost.log
  - intertos:
      panes:
        - pane_with_multiple_commands:
           - tmux -CC attach new-session -A -s epdevbox
           - /bin/zsh
           - source ~/.zshrc
