[tool.black]
line-length = 120
skip-string-normalization=true
target-version = ['py37']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''

[tool.isort]
profile = true
line_length=120
indent=4
force_grid_wrap=true
ensure_newline_before_comments = true
lines_after_imports=2
include_trailing_comma=false
use_parentheses=false
